version: '3.4'
services:

  # frontend
  suppbery-admin:
    container_name: suppbery-admin 
    build: ./frontend/cost-planner
    ports:
     - "4200:4200"
    volumes: 
     - "/home/roman/repository/frontend/cost-planner/sources:/angular/suppbery-admin"
    network_mode: host

  #auth-service
  auth-service:
    container_name: auth-service
    restart: always
    build: ./backend/microservices/auth-service
    ports:
     - "8081:8081"
     - "9081:9081"
    depends_on:
      - auth-db
    links: 
      - auth-db:auth-db
  #  networks:
  #    - frontend
  #    - backend

  # auth-db
  auth-db:
    container_name: auth-db
    hostname: auth-db
    image: mysql:latest
    ports: 
      - "3306:3306"
    volumes: 
      - "/home/roman/backup_database/mysql/auth-db:/var/lib/mysql"
    environment: 
      - "MYSQL_ROOT_PASSWORD=123"
      - "MYSQL_DATABASE=auth-db"
      - "MYSQL_TCP_PORT=3306"
   # networks:
    #  - backend


  #menu-service
  menu-service:
    container_name: menu-service
    restart: always
    build: ./backend/microservices/menu-service
    ports:
     - "8082:8082"
     - "9082:9082"
    depends_on:
      - menu-db
    links:
      - menu-db:menu-db
      - auth-service:auth-service
         # networks:
    #  - frontend
    #  - backend

  # menu-db
  menu-db:
    container_name: menu-db
    hostname: menu-db
    image: mongo:latest
    volumes: 
      - "/home/roman/backup_database/mongodb/volume/menu-db:/data/db"
    ports: 
      - "27017:27017"
   # networks:
    #  - backend

  # setting network with all containers
#networks:
 # frontend:
  #backend:
