version: "3.4"
services:
 
       
  #frontend
  #  b2b:
  #  container_name: b2b
  #  image: greenfield0000/b2b-front:5.0.4
    #    build: frontend/admin/sources/dist/
    #   ports:
    #    - "4200:4200"
        # volumes:
        #  - "~/repository/deliveryfood/frontend/admin/sources:/angular/interface-admin"
        #    network_mode: host

  #auth-service
  auth-service:
    container_name: auth-service
    image: greenfield0000/auth-service:1.0.1
    ports:
      - "8081:8081"
      - "9081:9081"
    depends_on:
      - central-db
      - gateway-service
    links:
      - central-db:central-db

  #menu-service
  menu-service:
    container_name: menu-service
    image: greenfield0000/menu-service:1.0.1
    ports:
      - "8082:8082"
      - "9082:9082"
    depends_on:
      - central-db
      - gateway-service
    links:
      - central-db:central-db
      - auth-service:auth-service

  #journal-service
  journal-service:
    container_name: journal-service
    image: greenfield0000/journal-service:1.0.1
    restart: always
    ports:
      - "8083:8083"
      - "9083:9083"
    depends_on:
      - central-db
      - gateway-service
    links:
      - central-db:central-db

  # fias-kladr-service
  kladr-service:
    container_name: kladr-service
    restart: always
    image: greenfield0000/kladr-service:1.0.0

  #gateway-service
  gateway-service:
    container_name: gateway-service
    restart: always
    image: greenfield0000/gateway-service:1.0.0
    ports:
      - "8080:8080"
      - "9080:9080"
  
  central-db:
    container_name: central-db
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=rootuser
      - POSTGRES_DB=central-db
      - PGDATA=/var/lib/postgresql/data/pgdata/central-db
    volumes:
      - "~/backup_database/postgres/central-db:/var/lib/postgresql/data/pgdata/central-db"

  personal-service:
    container_name: personal-service
    image: greenfield0000/personal-service:1.0.1
    ports:
      - "8079:8080"
      - "9079:8787"
    depends_on:
      - central-db

  kitchen-service:
    container_name: kitchen-service
    image: greenfield0000/kitchen-service:1.1.0
    ports:
      - "8084:8085"
      - "9085:9085"

