apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: front-gateway-ingress
  #  annotations:
  #  ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: deliveryfood.com
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 4200


