apiVersion: v1
kind: Service
metadata:
  name: b2b-front
spec:
  selector:
    app: b2b-front
  ports:
  - name: http
    protocol: TCP
    port: 8080
    nodePort: 30200
  - name: https
    protocol: TCP
    port: 8443
    nodePort: 30200
  type: NodePort
