apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  ports:
    - port: 8081
      targetPort: 4200
  selector:
    app: frontend
  type: LoadBalancer
