apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
            #app: frontend
      app: bus-layer
  template:
    metadata:
      labels:
              #app: frontend
        app: bus-layer
    spec:
      containers:
      - name: b2b-front
        image: greenfield0000/b2b-front:v5.0.1
        ports:
        - containerPort: 4200
