apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  ports:
    - port: 4200
      targetPort: 4200
  selector:
    app: frontend
  type: NodePort
  # NodePort for local developing (this need LoadBalancer)
