apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: default
spec:
  ports:
    - port: 4201
      targetPort: 4201
  selector:
    app: frontend
  # NodePort for local developing (this need LoadBalancer)
