apiVersion: v1
kind: Service
metadata:
  name: auth-db
  labels:
    environment: dev
    tier: db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    environment: dev
    tier: db

#-----------------------------

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: auth-db
  labels:
    environment: dev
    tier: db
spec:
  selector:
    matchLabels:
      environment: dev
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        environment: dev
        tier: db
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-database
              key: database
        - name: MYSQL_TCP_PORT
          valueFrom:
            secretKeyRef:
              name: mysql-port
              key:  port
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

