apiVersion: v1
kind: Service
metadata:
  name: auth-db
  labels:
    environment: dev
    tier: db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    environment: dev
    tier: db
  clusterIP: None
