apiVersion: v1
kind: Service
metadata:
  name: auth-db
  labels:
    app: auth-db
spec:
  ports:
    - port: 3306
  selector:
    app: auth-db
    tier: mysql
  clusterIP: None

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: auth-db
  labels:
    app: auth-db
spec:
  selector:
    matchLabels:
      app: auth-db
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth-db
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-database
              key: database
        - name: MYSQL_TCP_PORT
          valueFrom:
            secretKeyRef:
              name: mysql-port
              key:  port
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

