apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine-deployment
  labels:
    app: redmine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
        - name: redmine
          image: gcr.io/deliveryfood/greenfield0000/redmine:v1
          ports:
            - containerPort: 3000
        - name: mysql-redmine
          image: gcr.io/deliveryfood/greenfield0000/mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: changeit
                #secretKeyRef:
                 # name: mysql
                 # key: password
          ports:
            - containerPort: 3306
              name: mysql
 #         volumeMounts:
#            - name: mysql-persistent-storage
  #            mountPath: /var/lib/mysql
   #   volumes:
    #    - name: mysql-persistent-storage
     #     persistentVolumeClaim:
      #      claimName: mysql-volumeclaim
